### ISSUE TITLE
Make Connect() more reusable

### ISSUE THREAD

**Issue by LuvForAirplanes** [LuvForAirplanes/Micanet-Browser#3]
Do **not** allow Connect() to automatically handle data returned by the server.  We will need to connect multiple times to different sources, so, I should be made more reusable.

This may be done by creating a class to do connections, and statically reference them. This may pose a problem when we attempt to change the Windows Forms Hoster's content  from a static void.

**Comment by micahstauffer** [comment]
Waiting on response from @StillLearnin
